apiVersion: v1  
kind: Service  
metadata:  
  name: expressjs-backend  
  namespace: default  
spec:  
  selector:  
    app: expressjs-backend  
  ports:  
    - protocol: TCP  
      port: 80  
      targetPort: 4000  